name: WikiRag

services:
  embeddings:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - huggingface_cache:/cache/huggingface
    environment:
      - HF_HOME=/cache/huggingface

volumes:
    huggingface_cache:
